services:

    #
    # Event Dispatchers
    #
    gearman.dispatcher.abstract:
        abstract: true
        arguments:
            - "@event_dispatcher"

    gearman.dispatcher.callbacks:
        class: "%gearman.dispatcher.callbacks.class%"
        arguments:
            - "@event_dispatcher"
        public: true
